"""Add table reservations

Revision ID: 38c6381a631b
Revises: 34820b658b8b
Create Date: 2023-09-01 14:29:22.202389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c6381a631b'
down_revision = '34820b658b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
