"""Six migration

Revision ID: 40e875131c26
Revises: e90b4b36ea97
Create Date: 2023-09-01 14:50:44.492490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e875131c26'
down_revision = 'e90b4b36ea97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
