"""Three  migration

Revision ID: e90b4b36ea97
Revises: 38c6381a631b
Create Date: 2023-09-01 14:48:17.509338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90b4b36ea97'
down_revision = '38c6381a631b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
